### PR TITLE
Dropped old migrations and recreated new migration scripts

### PR DESCRIPTION
**Pull request by nuwang**
Recreates the new migration scripts.

@afgane @machristie To update an existing development database which has all prior migrations applied, manually edit the django_migrations table and delete all migration entries except 0001_initial.

### CODE REVIEW

**Comment by afgane** [comment]
I deleted all migrations except `0001` for the baselaunch app from the database and when running `python manage.py migrate` I now get: `django.db.migrations.exceptions.NodeNotFoundError: Migration cloudlaunch.0001_initial dependencies reference nonexistent parent node ('djcloudbridge', '0002_auto_20171007_0736')`. My `djcloudbrige` migration is at `0001` and there's only one migration the djcb repo: https://github.com/CloudVE/djcloudbridge/tree/master/djcloudbridge/migrations

**Comment by nuwang** [comment]
Can you try now? I think django migrate had created an incorrect dependency. This has been fixed in: https://github.com/galaxyproject/cloudlaunch/commit/1a5ef53e75b1fc51b4e5cf128797c46230daa0cb

**Comment by afgane** [comment]
Applying the migration works now but all the data from the database (for the baselaunch/cloudlaunch app) is no longer there.

**Comment by nuwang** [comment]
Yes, the rename from baselaunch->cloudlaunch effectively kills it. The only way I can think of is to dump and export or manually edit sqlite and rename baselaunch->cloudlaunch

**Comment by afgane** [comment]
For anyone else doing this, here's a list of sqlite3 commands I ran to get the original data into the new tables. Do this after having applied the migration.
```
DROP TABLE cloudlaunch_appcategory;
ALTER TABLE baselaunch_appcategory RENAME TO cloudlaunch_appcategory;
DROP TABLE cloudlaunch_application;
ALTER TABLE baselaunch_application RENAME TO cloudlaunch_application;
DROP TABLE cloudlaunch_application_category;
ALTER TABLE baselaunch_application_category RENAME TO cloudlaunch_application_category;
DROP TABLE cloudlaunch_applicationdeployment;
ALTER TABLE baselaunch_applicationdeployment RENAME TO cloudlaunch_applicationdeployment;
DROP TABLE cloudlaunch_applicationdeploymenttask;
ALTER TABLE baselaunch_applicationdeploymenttask RENAME TO cloudlaunch_applicationdeploymenttask;
DROP TABLE cloudlaunch_applicationversion;
ALTER TABLE baselaunch_applicationversion RENAME TO cloudlaunch_applicationversion;
DROP TABLE cloudlaunch_applicationversioncloudconfig;
ALTER TABLE baselaunch_applicationversioncloudconfig RENAME TO cloudlaunch_applicationversioncloudconfig;
DROP TABLE cloudlaunch_cloudimage;
ALTER TABLE baselaunch_cloudimage RENAME TO cloudlaunch_cloudimage;
DROP TABLE cloudlaunch_image;
ALTER TABLE baselaunch_image RENAME TO cloudlaunch_image;
DROP TABLE cloudlaunch_usage;
ALTER TABLE baselaunch_usage RENAME TO cloudlaunch_usage;
```

**Comment by machristie** [comment]
Yeah those sqlite3 commands worked for me too.

One other thing I ran into, I had to change the backend_component_name for the Ubuntu ApplicationVersion from `baselaunch.backend_plugins.base_vm_app.BaseVMAppPlugin` to `cloudlaunch.backend_plugins.base_vm_app.BaseVMAppPlugin`.  I did that in the admin.

**Pull request merged**
