### PR TITLE
Added support for cluster and storage type selection. Also, centered for widescreen displays.

### PR DESCRIPTION
**Pull request by nuwang**

### CODE REVIEW

**Comment by afgane** [comment]
This is quite convenient and amazingly enough, it's (almost) working!

The only thing I feel should be changed is to use the same terminology for cluster types as in CloudMan?

Setting a custom volume size does not work (a default-size volume gets created instead) - this is probably an issue in CloudMan not reading the `pss` value over the one defined in a flavor template. 

(I'd work on some of this as well but am at a conference today and tomorrow so am likely to have only minutes at a time)

**Comment by nuwang** [comment]
I just realised that the I've been committing to the same branch and the pull request has been updated :-) Yes, I've just been making the necessary changes to cloudman and have been doing some refactoring as well. I'll push in the changes soon - just doing some final testing.

**Comment by nuwang** [comment]
About the terminology - I was wondering about that - it's just that "Test" cluster seems to suggest that it's just for Testing purposes? I was just wondering whether it would make sense to a first time user, hence the slight change in labelling - but I don't really mind either way.

**Comment by afgane** [comment]
Going back to the terminology - this is probably a good opportunity to revise the terminology in CloudMan itself because, as you say, there's probably a text that makes the intent more clear.

In the mean time, I'm merging this because it's a feature I'm very glad to finally see implemented.

**Pull request merged**
